# GoReleaser configuration
version: 2

project_name: domour-copilot

before:
  hooks:
    - npm install --prefix frontend
    - npm run build --prefix frontend

builds:
  - id: domour-copilot
    main: .
    binary: domour-copilot
    flags:
      - -tags=production
    ldflags:
      - -s -w -X main.appVersion={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    files:
      - "build/bin/domour-copilot.app"
    files_overrides:
      - goos: windows
        files:
          - "build/bin/domour-copilot.app"
      - goos: linux
        files:
          - "build/bin/domour-copilot.app"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  draft: false
  prerelease: false
