# GoReleaser configuration
version: 2

project_name: tars-copilot

before:
  hooks:
    - npm install --prefix frontend
    - npm run build --prefix frontend

builds:
  - id: tars-copilot
    main: .
    binary: tars-copilot
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  draft: false
  prerelease: false
