// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function About():Promise<string>;

export function ChatWithGemini(arg1:string):Promise<string>;

export function ChatWithGeminiWithAttachments(arg1:string,arg2:Array<main.GeminiAttachment>):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InstallVlink(arg1:string,arg2:string):Promise<string>;

export function IsVlinkInstalled():Promise<boolean>;

export function IsVlinkPortAlive():Promise<boolean>;

export function SelfUpdate():Promise<string>;

export function SelfUpdateFromArchive(arg1:string):Promise<string>;

export function StartVlink():Promise<string>;

export function StopVlink():Promise<string>;
