// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function About() {
  return window['go']['main']['App']['About']();
}

export function ChatWithGemini(arg1) {
  return window['go']['main']['App']['ChatWithGemini'](arg1);
}

export function ChatWithGeminiWithAttachments(arg1, arg2) {
  return window['go']['main']['App']['ChatWithGeminiWithAttachments'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallVlink(arg1, arg2) {
  return window['go']['main']['App']['InstallVlink'](arg1, arg2);
}

export function IsVlinkInstalled() {
  return window['go']['main']['App']['IsVlinkInstalled']();
}

export function IsVlinkPortAlive() {
  return window['go']['main']['App']['IsVlinkPortAlive']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelfUpdate() {
  return window['go']['main']['App']['SelfUpdate']();
}

export function SelfUpdateFromArchive(arg1) {
  return window['go']['main']['App']['SelfUpdateFromArchive'](arg1);
}

export function StartVlink() {
  return window['go']['main']['App']['StartVlink']();
}

export function StopVlink() {
  return window['go']['main']['App']['StopVlink']();
}
